### ISSUE TITLE
Actions Improvements: order of return values

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#104]
Some open issues were identified during the review of PR #103 
- Consistent order of the return values in the arrays (Which is the last action?)

**Comment by benfrancis** [comment]
Is this still necessary if actions have timestamps? https://github.com/w3c/wot-profile/issues/101

**Comment by mlagally** [comment]
The thing most likely puts action requests into a queue, so there's already a sort order, which could be guaranteed without cost.
If we do not add this constraint, the consumer has to perform sorting, which causes unnecessary overhead.
