### ISSUE TITLE
Eventing Mechanisms of Smart Home Solutions

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#108]
This was requested by @mlagally in the TPAC F2F.

I have looked into 3 open source smart home gateway projects to see how they do eventing. I think that this profile is not going in the direction of smart home use cases but I did my job anyway.

WebThings: Websocket with own message structure. See https://webthings.io/api/#web-thing-websocket-api
Home Assistant: Websocket with own message structure. See https://developers.home-assistant.io/docs/api/websocket
OpenHAB: SSE. See this thread: https://community.openhab.org/t/solved-openhab2-restapi-and-web-sockets/39701

So I don't think that introducing cloud events makes a lot of sense if smart home is one of the use cases. Having simple SSE and CloudEvents is a bit questionable in regards to the interoperability claims. If we are going to support multiple protocols and mechanisms, we go on the direction of TDs. Multiple mechanisms imply that all Consumers of this profile must understand all these mechanisms.

**Comment by benfrancis** [comment]
Since this appears to be background information for #107, I propose closing.
