### ISSUE TITLE
Blocker for publication

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#110]
Please mark all issues that block the Profile spec from being published wit thew label "blocks publication"

**Comment by benfrancis** [comment]
I've done a first pass of existing issues, I plan to add some new ones tomorrow.

@mlagally In triaging the issues, I marked all issues that I think could now be closed with the label "close-next-week". Apologies if this isn't the intended purpose for this label but unfortunately whilst I have the permission to apply labels to issues I don't have permission to create new label like "propose-closing" :)

Hope this is helpful.
