### ISSUE TITLE
Add Discovery section to Core Profile

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#112]
Previously suggested in https://github.com/w3c/wot-profile/issues/73#issuecomment-804252286 and https://github.com/w3c/wot-profile/pull/78.

I propose adding a subsection to the WoT Core Profile section called "Discovery" which defines the discovery mechanisms (if any) which Core Profile conformant Consumers MUST support.

From https://github.com/w3c/wot-profile/pull/78#discussion_r742900701:

> Of the introduction mechanisms defined by the WoT Discovery specification, I think [DNS-based Service Discovery](https://w3c.github.io/wot-discovery/#introduction-dns-sd) could be a candidate for a mandatory discovery mechanism in the Core Profile, but that may be asking too much.
> 
> My current thinking is that  [Direct](https://w3c.github.io/wot-discovery/#introduction-direct) discovery could be made the mandatory discovery mechanism by simply requiring that a Thing Description conforming to the Core Profile must be resolvable through an HTTP URL which can be manually typed or copy & pasted in order to locate the Thing Description.

**Comment by mlagally** [comment]
This is an interesting proposal which potentially may open up significant discussion about authentication etc.
However I do not think we need to include discovery to the 1.0 version of the profile specification before we can publish the specification. 
Note that discovery is not a TD feature and the spec is still evolving.
Describing discovery mechanisms is beyond the scope of the 1.0 spec.

**Comment by benfrancis** [comment]
@mlagally wrote:
> This is an interesting proposal which potentially may open up significant discussion about authentication etc.

I agree, and I think we're close to agreeing on a solution to that problem. See https://github.com/w3c/wot-discovery/issues/135

> Note that discovery is not a TD feature and the spec is still evolving.

The WoT Profile specification already depends on features of WoT Thing Description 1.1, so what's the reason it can't depend on features of WoT Discovery 1.0 which is on the same publication timetable?

> Describing discovery mechanisms is beyond the scope of the 1.0 spec.

I don't think this text defines a discovery mechanism, it just refers to the Direct discovery mechanism defined by the WoT Discovery specification. I would argue that it is in scope because not having a guaranteed way to retrieve a Thing Description is definitely a barrier to interoperability. If a Consumer can't retrieve a Thing Description for a Thing (e.g. because it isn't available via a protocol that the Consumer supports), how can it interact with it?

Without this requirement, how do you imagine a Consumer would consume a Thing Description?

**Comment by benfrancis** [comment]
In response to https://github.com/w3c/wot-discovery/issues/263...

---

My recommendation is that for discovery the Core Profile should just require support for:
1. [Direct introduction mechanism](https://w3c.github.io/wot-discovery/#introduction-direct)
2. [Self-description exploration mechanism](https://w3c.github.io/wot-discovery/#introduction-direct)

This is the simplest possible combination and basically just translates to making it mandatory that Thing Descriptions MUST be retrievable via an HTTP URL. I have drafted a section to this effect in #121. It already references the Direct introduction mechanism. I could also add a reference to the Self-description exploration mechanism which goes into a bit more detail about how the Thing Description is retrieved.

I would rather not make well-known URIs mandatory in Core Profile because:
1. It enforces a particular path segment for Thing Description URLs and only allows one discoverable Thing Description URL per host
2. It has unintended side effects (discussed in https://github.com/w3c/wot-profile/pull/121 and https://github.com/w3c/wot-discovery/issues/263)

We should separately consider whether we also want the Core Profile to make support for discovering directories mandatory as well, which would imply that all conformant Consumers would also have to implement the Directory Service API.
