### ISSUE TITLE
Add Links section to Core Profile

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#114]
Previously suggested in https://github.com/w3c/wot-profile/issues/73#issuecomment-804252286 and https://github.com/w3c/wot-profile/pull/78.

I have previously proposed adding a subsection to the WoT Core Profile section called "Links" which defines types of link relations which Core Profile conformant Consumers MUST support.

However, looking through the list of "[best practice relation type](https://w3c.github.io/wot-thing-description/#link)"s in the Thing Description specification I'm not sure there are any which actually make sense as being mandatory.

I had previously suggested that link `rel=alternate` with `type=text/html` could be used to denote an HTML user user interface in the web thing (we do this in WebThings), but in retrospect I'm not sure it's really possible to make this mandatory since supporting it assumes that a Consumer can render a web page to the user, which may not be the case for all consumers.

Are there any link relation types for which support should be mandatory in the Core Profile, or shall we just leave this out?

**Comment by mlagally** [comment]
I think we should include links that allow composition and aggregation of things to a larger structure to the profile.
There are names in the IANA registry that would be appropriate for these.

**Comment by benfrancis** [comment]
@mlagally wrote:
> I think we should include links that allow composition and aggregation of things to a larger structure to the profile.

This seems like quite an advanced feature for a core profile. Are there any existing implementations which provide implementation experience of something like this? Is this something you have plans to implement yourself?

See also: https://w3c.github.io/wot-thing-description/#thing-model-composition

**Comment by mlagally** [comment]
The profile includes a "Links" section, so we should close this issue. 
Conversations about individual requirements in the "Links" section are happening in separate issues.
