### ISSUE TITLE
single profile or smart home + industrial profile

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#12]
Questions from arch call on 5.9.:

- What would be the commonalities?

- What arguments are pro a single profile?

- Which specific differentiators do we have between a home and an industrial profile?

- Are these just differentiated by using different protocols, or are there different requirements for the core data/information model? 

- Can/Should we define a core default protocols (HTTP) ? 
This may not be useful in industrial use cases. The HTTP security model is not well defined in offline use cases.

**Comment by zolkis** [comment]
IMHO the variance among industrial applications, among smart home applications and than between smart home and industrial use cases is of similar magnitude.

Therefore I surmise this distinction would not add much value. We should make the TDs better in general in order to cope with the variance.

**Comment by benfrancis** [comment]
> What arguments are pro a single profile?

1. The World Wide Web is fundamentally a cross-domain technology. There is no consumer web and industrial web, any web browser can render any web page. The same should be true of WoT clients and WoT servers.
2. The first line of the current [Working Group Charter](https://www.w3.org/2016/12/wot-wg-2016.html) says "The Web of Things seeks to counter the fragmentation of the IoT through standard complementing building blocks (e.g., metadata and APIs) that enable easy integration across IoT platforms and application domains." Integrating _across_ application domains requires a layer of abstraction at the web layer which works *across* domains, not separate data models and protocols which further cement the differences between them.
3. We already have a mechanism for augmenting Thing Descriptions with domain-specific metadata through [semantic annotations](https://w3c.github.io/wot-thing-description/#semantic-annotations) where necessary, while maintaining compatibility of the underlying data model and protocols.

> Which specific differentiators do we have between a home and an industrial profile?

Please correct me if I'm wrong but I get the sense that the differentiators being discussed are not really about industrial vs. home use cases but are really about the desire to describe existing non-web protocols directly in a Thing Description.

In my opinion describing non-web protocols should be out of scope for a web standard. If your application doesn't use any web protocols then it may be an IoT application but it is not a WoT application. It therefore requires software to bridge it to the standard WoT data model and web protocols. I understand that some participants may want to use something like a Thing Description for non-web use cases, but I argue the World Wide Web Consortium is not a good place to define that standard.

> Can/Should we define a core default protocols (HTTP) ?

In my opinion there should be a standard for how communicate with a Web of Things device over web protocols. There are currently only two web protocols I am aware of:

1. HTTP
2. CoAP

> This may not be useful in industrial use cases. The HTTP security model is not well defined in offline use cases.

The need for [HTTPS on local networks](https://www.w3.org/community/httpslocal/) is not unique to industrial use cases.

**Comment by zolkis** [comment]
I have discussed the profiles idea with a few people and based on experience in various standardization efforts, the consensus was that
- profiles rarely solve the right problem in a right way,
- profiles (and other stuff, like early optimizations, added value/smartness etc) are usually made in the context of a given time and industrial environment, which then changes with time, but standards stay, and we tend to become stuck with beefed up standards that solve past problems. It's harder to change then.
- this is not to say the work on the profiles spec/Note should be dumped, as it contains valuable information and viewpoints; rather, we should strive to integrate the findings into the TD spec. Especially at this point of the standardization we should not diverge.

**Comment by benfrancis** [comment]
I agree, it would be much better for interoperability if we could keep the data model consistent across all application domains.

The profiles effort could instead focus on horizontal profiles which define standard ways to communicate with a web thing using a given protocol (without needing a custom protocol binding in a Thing Description).

**Comment by mlagally** [comment]
Defer to 2.0 since we are focussing on a limited set of identified requirements.

**Comment by mlagally** [comment]
We went on and defined a horizontal profile. Issue can be closed.
