### ISSUE TITLE
Consider removing the External TD representations section

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#122]
Originally proposed in https://github.com/w3c/wot-profile/pull/78

I propose removing the current [External TD representations](https://w3c.github.io/wot-profile/#external-td-representations) section because there is nothing in this section which isn't already defined in the Thing Description specification. These normative statements do not need repeating for the Core Profile and doing so risks the two specifications getting out of sync in the future.

**Comment by mlagally** [comment]
The canonical section in the TD spec is likely to be removed from the 1.1 version.
This has been discussed in recent main / editors calls. 

In this case the Canonicalisation section in the Profile needs to be preserved to make the existing protocol binding descriptions, that currently require the canonical form, work. Alternatively these descriptions could be simplified and have a direct description of how to resolve the form URL. 

This is the preferred approach, so if we want to pursue this MR, please also change the binding sections..

**Comment by benfrancis** [comment]
@mlagally wrote:
> The canonical section in the TD spec is likely to be removed from the 1.1 version.
> This has been discussed in recent main / editors calls.
> In this case the Canonicalisation section in the Profile needs to be preserved to make the existing protocol binding descriptions, that currently require the canonical form, work.

If that's the reason then the current definition of a canonical TD in the WoT Profile would not be sufficient. The JSON Canonicalization Scheme is only one part of the process described in the [canonicalisation process](https://w3c.github.io/wot-thing-description/#canonicalization-serialization-json) section of the Thing Description specification. The important part was that defaults should be made explicit. However...

> Alternatively these descriptions could be simplified and have a direct description of how to resolve the form URL.
> 
> This is the preferred approach, so if we want to pursue this MR, please also change the binding sections..

This has [already been done](https://github.com/w3c/wot-profile/pull/96), there's no mention of canonical TDs in the protocol binding any more.
