### ISSUE TITLE
Describe key use cases for Profiles

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#128]

**Comment by benfrancis** [comment]
Do use cases not belong in the [Use Cases and Requirements](https://w3c.github.io/wot-usecases/) document or the [Use Cases](https://www.w3.org/TR/wot-architecture/#sec-use-cases) section of the WoT Architecture specification? 

Note that the WoT Thing Description and WoT Discovery specifications do not have use cases sections.

**Comment by mlagally** [comment]
As explained on the last arch call, we summarize the use cases that are addressed by the profile to give the reader an introduction.

**Comment by mlagally** [comment]
As explained on the last arch call, we summarize the use cases that are addressed by the profile here.
