### ISSUE TITLE
simple location format

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#177]
Define a simple to use location format to represent latitude, longitude and altitude.

https://en.wikipedia.org/wiki/Geo_(microformat)
can serve as a reference how this could be solved.

**Comment by egekorkan** [comment]
There are issues about this in nearly every WoT repo at this point and the general consensus is to use other vocabularies such as the one from schema.org. I think that the profile should simply dictate the use of this ontology. See https://w3c.github.io/wot-thing-description/#semantic-annotations-example-geoloc
