### ISSUE TITLE
Handing the format keyword of JSON Schema

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#179]
The spec currently has:

>If the field format is used, formats defined in section 7.3.1-7.3.6 of [[JSON-SCHEMA](https://w3c.github.io/wot-profile/#bib-json-schema)] MUST be used.

This is in theory ok but different implementations of JSON Schema (validators, UI and code generators, etc.) treat the formats in different "lazyness" levels, like checking `@` sign for email or doing full regex validation. So we should at least add a note about this or find a proper solution otherwise we cannot have OOTBI. 

Note: the format keyword is removed in json schema drafts 2019-09 and above

**Comment by mlagally** [comment]
@egekorkan Rhanks for flagging this problem, which helped to discover a wrong refence.
We should update the link to refer to JSON Schema validation,
the latest draft is available at:
https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00
