### ISSUE TITLE
New section: Security considerations

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#182]
Point to corresponding section in TD spec.
For now we can add an ednote to describe that the section will be fleshed out in due course.

**Comment by benfrancis** [comment]
If there's going to be a top level Security Considerations section we may want to move the existing Note from section [6.4 Security](https://w3c.github.io/wot-profile/#security) inside the Core Profile to that section, since that note presumably applies to all profiles.

> Note
> 
> Please see [WoT Security Best Practices](https://w3c.github.io/wot-security-best-practices/) for implementation advice

**Comment by mmccool** [comment]
Note that Security Considerations and Privacy Considerations are *required* by the wide review process.  So it's not a question about whether we have them or not, it's what we put in them that we need to discuss.

**Comment by mlagally** [comment]
Please include a consideration discussing transport security.

**Comment by mlagally** [comment]
@mmccool, @benfrancis 
I have added the S&P considerations to a common section in https://github.com/w3c/wot-profile/pull/206

**Comment by mlagally** [comment]
We still have to move the section to an approprate location. Keeping the issue open.

**Comment by benfrancis** [comment]
I think this is done now and this issue can be closed.
