### ISSUE TITLE
New Section: Privacy Considerations

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#183]
Point to corresponding section in TD spec.
For now we can add an ednote to describe that the section will be fleshed out in due course.

**Comment by mmccool** [comment]
See https://github.com/w3c/wot-profile/issues/182 - as noted, these are required.  But yes, we can just point to the TD's S & P sections as a starting point.

**Comment by mlagally** [comment]
@mmccool, @benfrancis
I have added the S&P considerations to a common section in https://github.com/w3c/wot-profile/pull/206
