### ISSUE TITLE
Check RFC assertions / only single keyword per assertion

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#184]
Some assertions contain two keywords - these are breaking the tooling and should be split / reworded.

There's an occurrence in the Security section, probably there are others.

**Comment by chachamimm** [comment]
If some assertions of the Profile documentation are as the same assertions as other documentation, those assertions should be associated with them. Then, if those assertions have been validated in other documentations, those assertions don't need to validate in the Profile documentation.

**Comment by mlagally** [comment]
@chachamimm 
I agree that the profile does not have to validate assertions from the TD or architecture.
This Issue is addressing RFC assertions that are containing 2 keywords in a single assertion.
These will be fixed by https://github.com/w3c/wot-profile/pull/205

**Comment by mlagally** [comment]
resolven in #205
