### ISSUE TITLE
Consider splitting Use Cases & Requirements out into a separate document

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#190]
On one of the WoT Profile calls I said I would file an issue for this to be considered further along in the publication schedule.

I note that none of the other W3C WoT specifications include use cases and requirements in the text of the specification itself. I suggest splitting these out into a separate document inside the wot-profile repo.

**Comment by mlagally** [comment]
Profile call on 30.3.:
We should rename the "Use cases and Requirements" section to "Summary of use cases and requirements".
Refacoring the document is not planned.

**Comment by mlagally** [comment]
Arch call on April 24th: This is not a blocker but a proposed improvement, removing the "blocks publication" label.
