### ISSUE TITLE
How to get a renderable unit string?

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#196]
See feedback in https://github.com/w3c/wot-profile/pull/195
See for an example in a WoT testing: intel-wot-ha

**Comment by mlagally** [comment]
Thanks @benfrancis for the pointer. What is your reference for these localisations? Where are they defined?

The profile should reference the ontologies for these units and I hope we will also be able to add a normative reference to the localisations.

**Comment by benfrancis** [comment]
> Thanks @benfrancis for the pointer. What is your reference for these localisations? Where are they defined?

The GitHub link I provided is the original source. These localisations were provided specifically for the WebThings project by the open source community, via the [Pontoon](https://pontoon.mozilla.org/projects/webthings-gateway/) localisation service.

As far as I know, no standard specification exists which provides these kinds of localisations of unit names, and it wouldn't be feasible to define such a specification which covers all written languages on earth.

> The profile should reference the ontologies for these units and I hope we will also be able to add a normative reference to the localisations.

Ontologies only provide machine-readable semantic annotations for units. Where the human-readable equivalent differs, it needs to be provided by the developer of the Consumer which provides the user interface. This is why I say it's an implementation detail for Consumers. It isn't feasible to standardise human readable strings for every written language, so implementers need to add localisations for the markets which are important for their particular product.

This same approach is needed for other types of semantic annotations too (e.g. `schema:serialNumber`, `schema:manufacturer` and `saref:TemperatureSensor` in [Example 43](url) of the Thing Description specification) which are generic machine-readable terms not specific to a particular Thing instance.

Note that this is different from the `title`s and `description`s of instances of Things and their interaction affordances, for which device-specific human readable strings can be be defined in the Thing Description.
