### ISSUE TITLE
Update JSON-Schema reference to the latest draft

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#209]
See corresponding issues in TD spec:
https://github.com/w3c/wot-thing-description/issues/1513
https://github.com/w3c/wot-thing-description/issues/1514

**Comment by mlagally** [comment]
See also: https://github.com/w3c/wot-profile/issues/179

**Comment by benfrancis** [comment]
It appears that the conclusion for Thing Description was that [JSON-SCHEMA] already points at the most useful recent draft. I assume the same also applies here. Propose closing.
