### ISSUE TITLE
Wrong claim about use of the profile in plugfests

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#212]
The last paragraph at https://w3c.github.io/wot-profile/#deployment-scenarios says

> It has already proved in brown-field scenarios in the PlugFests, where existing devices, that already existed as products, prototypes or demonstrators, were described with Thing Descriptions that are constrained to the [Baseline Profile](https://w3c.github.io/wot-profile/#dfn-baseline-profile).

This is somewhat wrong. No Thing that existed before the profile has implemented the action mechanism that is completely new here. Of course, if a Thing only had properties they are probably profile conform but this claim is misleading

**Comment by mlagally** [comment]
This is very old text and has been valid some time in the past.
It needs to be updated after the next plugfest / fest.

**Comment by egekorkan** [comment]
This issue is addressed, closing
