### ISSUE TITLE
Wrong place to use HTTP Baseline Profile 

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#213]
HTTP Baseline Profile starts in section 6 however there are a lot of places before section 6 where it is mentioned. It seems that we should use only the word "Profile" in there.

**Comment by benfrancis** [comment]
The current text in the Abstract was written when only a single profile, the Core Profile, was defined in this first version of the WoT Profile specification. I think it needs re-wording to reflect the fact that multiple profiles are now defined.

**Comment by mlagally** [comment]
Can be closed after merge of #297

**Comment by mlagally** [comment]
Profile call on April 4th: close
