### ISSUE TITLE
Wrong sections/headers for HTTP profiles

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#214]
The section 6 is named `HTTP Profiles`. However, only the HTTP Baseline profile is put in there and the other HTTP Profiles are in section 7 and 8. They should be all in the same section

**Comment by benfrancis** [comment]
Furthermore, the HTTP Baseline Profile is currently a subsection of "HTTP Profile". I don't think the "HTTP Profile" section is needed, since there is no HTTP Profile. See #244

**Comment by mlagally** [comment]
Let's agree on the structure and content in the next call.

We currently have 3 profiles which share a lot of commonalities: They use TDs for describing affordances, have an identifier, use HTTP(S), security mechanism and have other common aspects and constraints, e.g. response codes, error responses, ...
These commonalities belong in a common section that is applicable to all profiles defined by our spec. This common section is section 6. We can change the name to any more suitable name. 

@egekorkan Please propose a name for that section.
 
Section 7.2 should be moved to this common section and then revised to describe the constraints we can agree on.

**Comment by egekorkan** [comment]
Well I find it a bit problematic to make a profile depend on another one so that is one major thing to discuss. If we agree on it, the section can be called HTTP Profiles. Why problematic? 
Well that means that any new HTTP would sort of depend on it and conform to it. It will make changes to other profiles more challenging. Also, the security is a big problem to define in a common way. There is a reason different mechanisms exist and limiting them (while having zero experience in the uses of them in profiles) is concerning to me.

**Comment by benfrancis** [comment]
@mlagally wrote:
> Let's agree on the structure and content in the next call.

Proposal:

- **HTTP Profiles**
  - **Common Constraints**
    - **Information Model** _(in my view this section should be omitted, with the only constraints being those defined in the sections below, see #10)_
    - **Security**
    - **Discovery**
    - **Links**
    - **Errors** _(I'm not completely sure this should be in common constraints because it's part of the protocol bindings and we might want to provide more specific guidance for individual operations)_
    - **Semantic Annotations** _(covering geolocation and units)_
  - **HTTP Baseline Profile** _(consider renaming to "Basic Profile" if "Baseline" implies a dependency)_
    - **Identifier**
    - **Protocol Binding**
  - **HTTP SSE Profile**
    - **Identifier**
    - **Protocol Binding**
  - **HTTP Webhook Profile**
    - **Identifier**
    - **Protocol Binding** _(which should include a message format which doesn't depend on Cloud Events, see #126)_
- **Privacy Considerations**
- **Security Considerations**


@egekorkan wrote:

> I find it a bit problematic to make a profile depend on another one so that is one major thing to discuss

I don't think we need a profile to depend on another one, just to have a common constraints section (not a profile itself) which multiple profiles reference. I would have preferred a single HTTP profile with a single event mechanism and no dependencies, but we are where we are.

> Well that means that any new HTTP would sort of depend on it and conform to it.

I agree that isn't ideal, but there's nothing to stop other HTTP profiles being defined in extension specifications which don't depend on the common constraints defined here.

> Also, the security is a big problem to define in a common way. There is a reason different mechanisms exist and limiting them (while having zero experience in the uses of them in profiles) is concerning to me.

I agree this area is lacking implementation experience.

**Comment by benfrancis** [comment]
@mlagally wrote:
> Let's agree on the structure and content in the next call.

We weren't able to discuss this in today's meeting, so to move the conversation forward I have prepared a [pull request](https://github.com/w3c/wot-profile/pull/260) with the proposed changes so you can see what it would look like.

The PR differs a little from what I described above in that:

1. HTTP Profiles Common Constraints, HTTP Baseline Profile, HTTP SSE Profile and HTTP Webhook Profile are all separate top level sections. The reason for this is that when I implemented what I proposed above the structure had five levels of nesting which seemed a bit excessive. I think this approach is more readable and easier to separate out if we need to (following the conversation today).
2. I've also left in the Default Language section in Common Constraints, and the Introduction and Message Format sections in the HTTP Webhook profile

At a high level, this looks like:

- HTTP Profiles Common Constraints _(open to a better name)_
  - Information Model
  - Security
  - Discovery
  - Links
  - Errors
  - Semantic Annotations
  - Default Language
- HTTP Baseline Profile
  - Identifier
  - Protocol Binding
- HTTP SSE Profile
  - Identifier
  - Protocol Binding
- HTTP Webhook Profile
  - Introduction
  - Identifier
  - Message Format
  - Protocol Binding
- Privacy Considerations
- Security Considerations

@mlagally Yes this is a big PR, but hopefully you can see it's necessary to demonstrate the proposal and we don't have to land it all in one go if there are disagreements.

**Comment by benfrancis** [comment]
Reopening to track the restructure proposed in https://github.com/w3c/wot-profile/issues/214#issuecomment-1211006519 and #260.
