### ISSUE TITLE
Example 3 is not compliant to the Profile

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#216]
At https://w3c.github.io/wot-profile/#common-fields, the text says:

> The field title is MANDATORY for Things, Property Affordances, Action Affordances, Event Affordances and Data Schemas. 

First of all, the span assertion is missing. Secondly, this says that all Data Schemas must have title but the [example 3](https://w3c.github.io/wot-profile/#example-3) does not have it for the input field of the `fade` action nor its input field `level`
```json
{
"actions": {
    "fade": {
      "title": "Fade",
      "description": "Fade the lamp to a given level",
      "input": {
        "type": "object",
        "properties": {
          "level": {
            "type": "integer",
            "minimum": 0,
            "maximum": 100,
            "unit": "percent"
          },
          "duration": {
            "type": "integer",
            "minimum": 0,
            "unit": "milliseconds"
          }
        }
      },
      "forms": [{"href": "actions/fade"}]
    }
  }
}

**Comment by benfrancis** [comment]
I will create a PR to add `title`s for the level and duration inputs. 

It doesn't really make sense in this case to provide a `title` for the `input` as a whole though, which is another good example of why that assertion should be removed altogether.
