### ISSUE TITLE
TD version dependency

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#217]
The spec is not clear about which version of the TD spec must be used. Example 3 uses 1.0 even though the terms that are required by the HTTP Baseline Profile such as `queryaction` are defined only in the TD spec V1.1 . 

I think that the profile spec should be very strict on this and say that only 1.1 TDs can be used.

**Comment by benfrancis** [comment]
@egekorkan Good catch.

I will create a PR to update the example to use 1.1.

The fact that TD 1.1 must be used is kind of implied by the assertion in section 5:

> In order to denote that a given [Web Thing](https://www.w3.org/TR/wot-architecture/#dfn-thing) conforms to one or more profiles, its Thing Description MUST include a[ profile](https://w3c.github.io/wot-thing-description/#thing) member [[wot-thing-description11](https://w3c.github.io/wot-profile/#bib-wot-thing-description11)]. The value of the profile member MUST be set to either a valid URI [[RFC3986](https://w3c.github.io/wot-profile/#bib-rfc3986)] identifying a single profile, or an array of valid URIs identifying multiple profiles.

Do you think we need to explicitly say that the `@context` member must also include the TD 1.1 context?

**Comment by egekorkan** [comment]
> Do you think we also need to explicitly say that the @context member must include the TD 1.1 context?

I think that this is needed.
