### ISSUE TITLE
Common Rules apply to all profiles

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#219]
Currently, the common rules section say:

> The following sections are applicable for all profiles defined by this document. 

Should it be all profiles or only HTTP profiles? The sentence is under HTTP profiles so it is a bit weird that it makes an "assertion" for the entire document. 

I have explicitly put quotes around "assertion" since the sentence itself has no RFC assertion, thus nothing binding for implementations

**Comment by mlagally** [comment]
We have now a section "Common Constraints". Suggest to close.
