### ISSUE TITLE
Example 46 is not about subscribeallevents

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#223]
[Example 46](https://w3c.github.io/wot-profile/#example-46) is in the `subscribeallevents` section. However, the URL in the request seems to be for a single event.

**Comment by mlagally** [comment]
@egekorkan 
I checked the examples in the spec and do not see the problem anymore, so this issue seems to be a leftover.
Can you please doublecheck  and close it in this case?

**Comment by mlagally** [comment]
Profile call on April 4th: This is addressed
