### ISSUE TITLE
remove http-webhook-profile-protocol-binding-general-2 assertion

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#229]
There is an assertion with id `http-webhook-profile-protocol-binding-general-2` and text `The HTTP Webhook profile MAY be used as an alternative event mechanism to the [HTTP SEE Profile](https://w3c.github.io/wot-profile/#sec-http-sse-profile).`

I think this assertion is not necessary and it cannot be tested in any way. I think it should be removed

**Comment by mlagally** [comment]
@egekorkan Please explain why you think it is not necessary.
We define 2 event mechanisms, Each of them MAY be used or they MAY be used together.

**Comment by egekorkan** [comment]
Any assertion that cannot be tested (automatic or manual), thus asserted, cannot be in a spec and it's actually not an assertion. I'm not saying that this doesn't make sense, it should simply not be an RFC assertion.

**Comment by egekorkan** [comment]
Any assertion that cannot be tested (automatic or manual), thus asserted, cannot be in a spec and it's actually not an assertion. I'm not saying that this doesn't make sense, it should simply not be an RFC assertion.
