### ISSUE TITLE
Core/default profile should mandate HTTP support as a minimum requirement

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#24]
In #19 it is suggested that the core/default profile should somehow be kept protocol agnostic, with "clarifications" for multiple individual protocols.

If the profile does not specify at least one protocol which _all_ conforming clients and servers must support, then any other constraints will have no benefit to interoperability.

Imagine we decided that we will no longer conduct W3C WoT meetings in English, we will all speak in our native languages. Some members can speak Spanish, some in German and some in Chinese. As long as we all state our names, location and date of birth and be sure to speak in short sentences, then presumably we will all be able to understand each other? This is obviously not the case, and the same is true for the Web of Things. If a client and server do not speak the same protocol, no set of additional constraints will allow them to communicate with each other.

I therefore propose that the core/default profile should mandate HTTP as a minimum requirement and have the freedom to explain exactly how to communicate with devices over HTTP without trying to remain protocol agnostic.

The Thing Description is protocol agnostic, but profiles can not be protocol agnostic if they are to meet the goal of enabling ad-hoc interoperability.

**Comment by egekorkan** [comment]
:+1: and also I think some protocols, like (JSON-RPC etc.) that work over HTTP should be also "banned" since they generally require significant implementation effort where we cannot say that any HTTP client can support it.

**Comment by benfrancis** [comment]
Closing since the Core Profile protocol binding does now require HTTP. Closed by https://github.com/w3c/wot-profile/pull/77
