### ISSUE TITLE
Consider making security bootstrapping mandatory in the HTTP Baseline Profile

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#250]
This is a follow-up to #121 (which adds a Discovery section to the HTTP Baseline Profile), to address the following issue:

> The WoT Discovery specification now describes another mechanism in [7.1.2 Security Bootstrapping](https://w3c.github.io/wot-discovery/#exploration-secboot) which uses HTTP 401, 302 or 303 response codes (depending on the security mechansim being used). Support for this bootstrapping mechanism is not currently mandatory for either Producers or Consumers, so as things stand only unauthenticated Thing Descriptions (consumed by Consumers which support HTTP and a Direct introduction mechanism) are guaranteed to be discoverable with the above addition to the HTTP Baseline Profile.

In order to support the discovery of authenticated Thing Descriptions (which I imagine in practice will be the majority of Thing Descriptions), we could make support for the [security bootstrapping mechanism](https://w3c.github.io/wot-discovery/#exploration-secboot) defined in the WoT Discovery specification mandatory for Consumers complying with the HTTP Baseline profile.

A bootsrapping mechanism would need to be supported for each of the mandatory security schemes (see also: #220).

**Comment by mlagally** [comment]
This was addressed in #121 and can be closed.

**Comment by benfrancis** [comment]
The discovery section doesn't mention security bootstrapping, this issue has not been resolved.

**Comment by mlagally** [comment]
Enforcing a specific security bootstrapping mechanism as part of the baseline profile would raise the implementation burden significantly. It won't be necessary in deployments to a trusted environment and should be further discussed in the Profile 2.0 work.

**Comment by benfrancis** [comment]
@mlagally wrote:
> It won't be necessary in deployments to a trusted environment and should be further discussed in the Profile 2.0 work.

Security bootstrapping is only not necessary for Thing Descriptions which are unauthenticated, but my expectation is that in practice the majority of Thing Descriptions will require authentication because they may contain sensitive metadata which should not be public.

If this is correct, then it currently means the majority of Things will not be useable by Consumers.

For example, WebThings Gateway requires authentication to access Thing Descriptions of devices, because for obvious reasons users do not want there to be a publicly accessible list of all of the smart devices in their home or commercial building. The authentication mechanism uses JSON Web Tokens in an Authorisation header of HTTP requests. Tokens can be requested using OAuth2, by the user entering a username and password.

Currently the Discovery section says that all Thing Descriptions must be retrievable from an HTTP server, but that is only the first step.

If a Consumer performs a GET request on an authenticated Thing Description, they will initially get an error response (401, 302 or 303). The Consumer needs to know what to do with that response, and follow the authentication flow (prompting a user for a username and password where necessary) in order to successfully retrieve the Thing Description.

If we don't require that Consumers support security bootstrapping for the required security schemes, then they will not be able to Consume the majority of Thing Descriptions.

I am happy to draft some text for this, but first we need to agree on a reduced set of required security schemes in https://github.com/w3c/wot-profile/issues/220. (The current list of required security schemes is a far bigger implementation burden than supporting security bootstrapping).
