### ISSUE TITLE
Human readable documentation

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#27]
Proposal:
Human readable documentation couldbe either contained in the the TD itself or is contained in a referenced template.
Whe a template is applied it would be possible to omit the human readable fields from the TD.

Discussion: 
Should a TD be self contained or a does a client have to resolve dependencies? 

A developer needs documentation during *development time*,  during the *usage by automation*  of a thing the human readable documentation is not used / required anymore.

Building a UI is the 3rd use case.

4. Offline UI.

**Comment by benfrancis** [comment]
I suggest moving this to the Thing Description repository.

**Comment by mlagally** [comment]
Not planned for Profile 1.0
