### ISSUE TITLE
Feedback on Profile document

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-profile#280]
(based on https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/272.html)

## General

Different spellings across the document: PlugFests, Plugfests, ..

## Typos

see https://github.com/w3c/wot-profile/pull/279

## Abstract
see https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/272.html#abstract

There is the following statement

> The HTTP Baseline Profile formalizes the results of several PlugFests that were conducted by the WoT Interest Group and of tests that were conducted as part of the development.

This is simply *not* true and I suggest to reword/remove this statement.

## 3.1 Additional Definitions

see https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/272.html#additional-definitions-

Baseline Profile vs. HTTP Baseline Profile
Personally... I would stick to use *one* term. Using "Baseline Profile" may raise other expectations. Hence "HTTP Baseline Profile" seems to be the term to go with.

# 7.2.2 Actions

see https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/272.html#http-baseline-profile-protocol-binding-actions

There is https://github.com/w3c/wot-profile/pull/266 from @benfrancis.
What are the expectations here?

**Comment by mlagally** [comment]
> (based on https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/272.html)
> 
> ## General
> Different spellings across the document: PlugFests, Plugfests, ..
> 
> ## Typos
> see #279
> 
> ## Abstract
> see https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/272.html#abstract
> 
> There is the following statement
> 
> > The HTTP Baseline Profile formalizes the results of several PlugFests that were conducted by the WoT Interest Group and of tests that were conducted as part of the development.
> 
> This is simply _not_ true and I suggest to reword/remove this statement.
> 
> ## 3.1 Additional Definitions
> see https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/272.html#additional-definitions-
> 
> Baseline Profile vs. HTTP Baseline Profile Personally... I would stick to use _one_ term. Using "Baseline Profile" may raise other expectations. Hence "HTTP Baseline Profile" seems to be the term to go with.
> 
> # 7.2.2 Actions
> see https://pr-preview.s3.amazonaws.com/w3c/wot-profile/pull/272.html#http-baseline-profile-protocol-binding-actions
> 
> There is #266 from @benfrancis. What are the expectations here?

This has been true when the first draft of the profile spec was written.

It will become true again, when we have conducted the next plugfest, assuming we get enough participants.
In the meantime, please understand that we just keep the inaccurate text.
