### ISSUE TITLE
Consider removing empty section 6.7 Semantic Annotations

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#284]
Since #137 and #29 have been tagged as being postponed until Profile 1.1, should I close PR #264 and remove section 6.7 Semantic Annotations?

**Comment by mlagally** [comment]
@benfrancis 
> Since #137 and #29 have been tagged as being postponed until Profile 1.1, should I close PR #264 and remove section 6.7 Semantic Annotations?

removing section 6.7 is appropriate, however please preserve the contents of PR #264. Following the suggestion from @mmccool , we could define this as a separate Profile or capability.

**Comment by benfrancis** [comment]
Closed in https://github.com/w3c/wot-profile/pull/288
