### ISSUE TITLE
Annotate the data model with common elements

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#31]
Examples include:
Accuracy
Timestamps 
Geolocation Information

These could be handled by annotations:
For accuracy we could allow SSN as an extension
Geolocation may also be handled by an extension
timestamps

**Comment by benfrancis** [comment]
I don't think I understand this issue, what exactly are you suggesting? I don't think we need to "allow" extensions as they are already allowed by default. Propose closing.
