### ISSUE TITLE
Brief section to describe a Consumer

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#322]
We use the term "Consumer" in many areas of the spec without specifically describing it.
Recent conversations showed that we need additional clarifications.

We need to add a brief section that describes Consumers with WebHooks

**Comment by egekorkan** [comment]
I think the explanation should go into the arch spec and ve aligned with the already existing terminology

**Comment by mlagally** [comment]
Arch call on Dec 21st:
Add text to the Webhook section that explains the specifics of the Message endpoint.
@egekorkan will combine proposed text with https://github.com/w3c/wot-profile/issues/328
