### ISSUE TITLE
Property forms in Example 23 missing SSE subprotocol

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#398]
I've noticed that the Forms in Example 23 are missing a `subprotocol `member to denote that the endpoints supports SSE.

There should probably be two forms for each of the property affordances, both with the same value for `href` but one with `op` set to `["readproperty", "writeproperty"]` and the other with `op` set to `["observeproperty", "unobserveproperty"]` and `subprotocol` set to `sse`.

**Comment by benfrancis** [comment]
I think this is actually a duplicate of #370 🤦

**Comment by mlagally** [comment]
@benfrancis Can we close this issue and continue in #370?
