### ISSUE TITLE
Events are loosely constrained

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#42]
- The events section is way too loose to allow out-of-the-box-interop (OOTBI). With WS in there, OOTBI is impossible, similar-ish with WebHooks. No experience at all with both of them from the plugfests. If this spec is not bringing OOTBI, its main argument to exist becomes less obvious.
- Any restriction in subprotocols?

Non-optimal solution: Allow only longpoll for events in HTTP.

**Comment by mlagally** [comment]
Discussion in arch call on 7.10.:
Use Longpoll for now, since we have experience with it, explore SSE at a later time. 

For performance we may want to use websockets at a later point in time in a future spec.

**Comment by relu91** [comment]
Also, the spec should refer to them as *subprotocols*:
> The supported protocols for events are WebHooks, WebSockets, SSE and Long polling.

*The supported subprotocols for HTTP(S) are: WebHooks, SSE, and Long polling*
