### ISSUE TITLE
FPWD Feedback from Daniel

### ISSUE THREAD

**Issue by danielpeintner** [w3c/wot-profile#43]
Please find below my feedback on "WoT Profile, 05 October 2020"

### 1.2 Why a Core Profile? 

2nd para "plug fest" vs "plug-fests" elsewhere in this document.
Note: We seem to use "PlugFest" usually.

### 4.1 Methodology

"per string, Always" --> "per string. Always"

### 5.1 WoT Core Data Model

"datamodel" --> "data model"

### 5.1.1 General

"WoT Thing Description Specification" --> "WoT Thing Description specification"

### 5.1.1.1 Mandatory fields

"Therefore the fields" --> "Therefore, the fields "

### 5.1.1.2 Length and Value Limits

"Where a type permits using an array of string or a string , an array of string MUST be used. "

Not sure if this is actually desired. 
`@type` is for example of this kind and would mean every core profile td would not allow the following
`"@type": "Thing"`

@context is anyURI or Array (does this fall into this category also?)

### 5.1.2.2 Recommended practice

"It is RECOMMENDED to use the value "Undefined" for strings, where the value cannot be determined."

I am not sure whether "Undefined is the right choice. How can one be sure whether "Undefined" is not what it should be. Usually undefined  means there is no value but that does not work given that terms might be required so  shouldn't we use "" instead?

### 5.1.3 Data Schemas --> Data Schema Constraints

The table lists
"one of boolean, integer, number, string, object or string"
while the text
"The values object , array , or null MUST NOT be used in the type field."
indicates that object should not be used ?

### 5.1.5 Interaction Affordance

The title should be "Action Affordance"

### 5.1.6 Event Affordances

title singular? "Event Affordance"

### GENERAL COMMENTS

- the "Data Schema Constraints" should be consistent over all affordance classes. I don't really see why there should be differences.

- Inconsistency in the use of the "Mandatory fields" tables.
column "type", "output", "input" and "data" should use the same form..
At the moment
  - properties use "one of boolean , .." 
  - actions/events use "all elements of the subclasses objectSchema"

**Comment by relu91** [comment]
> Not sure if this is actually desired.
> @type is for example of this kind and would mean every core profile td would not allow the following
> "@type": "Thing"
> @context is anyURI or Array (does this fall into this category also?)

I see no problem with constraint also those fields. Besides `"@type":["Thing"]` is still a valid JSON-LD field isn't it?. I think that having just one type of value for a field simplifies a lot any parser/validator.

**Comment by mlagally** [comment]
@danielpeintner 
The Profile-1.0 document has been gone through significant reworking, and I believe all non-editorial comments are resolved.
I suggest we close this issue.
