### ISSUE TITLE
FPWD Feedback by Sebastian

### ISSUE THREAD

**Issue by sebastiankb** [w3c/wot-profile#45]
In the current draft, I miss some editorial notes about unclearified discussions in the group such as about the "name" Core Profile and its impact (also see #21 and #25). 

In general, I miss some explanation about Figure 1 & 2 otherwise there will be misunderstanding about the profile concept such as that the "core" have to be always present in other possible profiles. I think this is not desired when I think about constrained profiles etc.

**Comment by sebastiankb** [comment]
@mlagally I can provide a PR about this today

**Comment by mlagally** [comment]
@sebastiankb 
We have added editor's notes that should be addressing your comments.

Cany you please check/confirm that your comments are addressed?
