### ISSUE TITLE
FPWD Feedback from Cristiano

### ISSUE THREAD

**Issue by relu91** [w3c/wot-profile#49]
### Security Element
In current spec, the security element allows an array of strings. However, as far as I know, it is not well tested/understood feature of the TD. For example, `node-wot` does not implement this mechanism. Considering that in the future TD will have a dedicated `SecuritySchema` to handle combinations, should we constraint this field to just a simple `string`?

### [Data Schema Constraints](https://w3c.github.io/wot-profile/#constraints-against-the-td-specification)

Format type constraint as the others (i.e. in section 5.1.4): one of boolean, integer, number, string, array or object -> one of boolean , string , number , integer , object or array . The type value null MUST NOT be used.

### [Action Affordances](https://w3c.github.io/wot-profile/#x5-action-affordances)
objectSchema -> ObjectSchema (probably we could also link it to TD spec)

**Comment by mlagally** [comment]
Arch call on 21.1.:
Security related comment willl be discussed in next call,
@relu91 will create a MR for the other two topics.

**Comment by mlagally** [comment]
@relu91 
The corresponding text on DataSchema constraints and Action Affordances is no longer part of Profile-1.0
Security related questions are discussed in several other issues, e.g. https://github.com/w3c/wot-profile/issues/221 and https://github.com/w3c/wot-profile/issues/220.

Suggest to close this issue.
