### ISSUE TITLE
Encrypted TDs

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#56]
We should define a way to encrypt/decrypt TDs to make sure the content can be protected.

**Comment by mlagally** [comment]
We should consider JSON Web Encryption as a viable candidate: https://tools.ietf.org/html/rfc7516

However it may be necessary to pick additional constraints, e.g. the required/permitted security algorithms.

**Comment by benfrancis** [comment]
What are the use cases for encrypted TDs which can't be fulfilled by TLS encryption during transport? Are there concrete use cases for encrypting TDs at rest?

**Comment by mlagally** [comment]
Arch call on 17.12.:
TDs may contain PII or other orivacy sensitive data that needs to be protected.
You can also pass on TDs via (unencrypted) mail.

**Comment by benfrancis** [comment]
Suggest moving to Thing Description repository.
