### ISSUE TITLE
Allow multiple forms for interaction affordances in Core Profile

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#60]
Section [5.1.4.2 Additional Constraints](https://www.w3.org/TR/2020/WD-wot-profile-20201124/#additional-constraints) of the First Public Working Draft says:
> The Array of Form of each property MUST contain only a single endpoint for each operation readproperty, writeproperty, observeproperty, unobserveproperty.

This constraint has the effect of preventing a WoT producer from supporting multiple protocols for its interaction affordances whilst conforming with the Core Profile. This seems like an unnecessary constraint as it doesn't help interoperability and may even prevent a WoT producer from conforming to multiple profiles.

I propose that this constraint should be dropped so that it's possible for a WoT device to be conformant with the Core Profile (e.g. using the default HTTP protocol binding) whilst also exposing endpoints using other protocols (e.g. WebSockets).

This would also make it easier to modify brownfield devices to make them conformant with the Core Profile, by allowing them to add new endpoints conforming to the Core Profile whilst continuing to expose other endpoints using legacy protocols and protocol bindings.

See also: https://lists.w3.org/Archives/Public/public-wot-wg/2020Dec/0025.html

**Comment by mlagally** [comment]
Arch call on 21.1.:
This has been written with multple forms for the same protocol in mind.
Need to revisit and could constrain to "only one form per protocol."

**Comment by mlagally** [comment]
There's an overlap of this issue with #141

**Comment by benfrancis** [comment]
Note: As I understand it this issue is about removing the current constraint which forbids multiple forms per interaction affordance and #141 is about how a Consumer should choose between multiple forms if they exist.

**Comment by relu91** [comment]
> Need to revisit and could constrain to "only one form per protocol."

As @sebastiankb mentioned in https://github.com/w3c/wot-profile/pull/125#issuecomment-966199892: 
> I also see a problematic conflict that forms should only have one entry. Servients can have typically multipile IP addresses such a local IP and global IP address. Sometimes you get also variations for IPv4 and IPv6. note-wot is the best example of how multiple form entries are possible even for a single protocol like http. Depending on where the consumers host, they can choose a local or global IP address for interaction.

Having multiple networks interfaces is pretty common in our set-ups. Forcing to have just one form per-protocol means that users will need to spawn N WebThings (most of which will be just proxies) with N equal to the number of the networking interfaces. I'd rather have a well-defined algorithm to choose a form as requested in #141.

**Comment by benfrancis** [comment]
The constraint on multiple forms was removed. Closing.
