### ISSUE TITLE
Max size of a Core Profile-compliant TD

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#66]
A maximum size limit of a profile compliant TD will ensure that the TD can be handled by resource constrained devices.
A practical size limit is to stay below 2^16-1 bytes (65535).
To avoid potential buffer overruns / off -by-one problems, the actual limit could be 65000.

**Comment by mlagally** [comment]
Arch call on 28.1.:
32k could also be enough - 2's complement might cause some issues.

**Comment by sebastiankb** [comment]
Which kind of resource constrained devices and scenarios do you have in mind?

**Comment by mlagally** [comment]
@sebastiankb 
Please see the comments in https://github.com/w3c/wot-profile/issues/67
We have not yet selected a refernce device, but there are some constraints of typical small embedded CPUs.

**Comment by benfrancis** [comment]
This is another example of a constraint which is important for constrained devices but could unnecessarily harm human readability for a less constrained device. Given the vast variety in hardware capabilities I'm not sure how helpful it is to set arbitrary limits like this. But if this kind of constraint is included in a profile I'd suggest this is further evidence for the need for separate "core" (HTTP+JSON) and "constrained" (CoAP+CBOR) profiles. If a device has enough resources to use HTTP then a 32KB sized resource is unlikely to be a problem.

**Comment by sebastiankb** [comment]
@mlagally #67 is talking about an UI use case and not about constrained embedded devices

Edge devices may offer over 1000 properties. No chance to follow such a Profile constraint.

**Comment by benfrancis** [comment]
Setting an arbitrary size limit is silly, I propose closing this.
