### ISSUE TITLE
Reference Device Definition for the smallest possible platform for HTTP / TCP / JSON

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#68]
Use Case: Process a full TD without additional external components:

- Producer: Enable telemetry / control to other devices.
- Consumer: Extracting pieces of information from a single TD to control or read telemetry data from some other device.

These devices are simple consumers/producers that just are required to consume a SINGLE TD.
Define a minimum device which can run a TCP / HTTP stack + JSON and consume / expose TDs.

Working assumption: 256K/[512] KB  RAM / 512 KB Flash
We can consider even 64K / 128K 

This has been proven to be enough to produce TDs. (Implementation in C with various libs, MicroPython would be an alternative)

@mryuichi : What is the typical size of an ECHONET device?

---
Other categories / classes are defined elsewhere, but they appear to be too restricted for a WOT stack:

IETF constrained device classes from: https://datatracker.ietf.org/doc/rfc7228/

 | Name        | data size (e.g., RAM) | code size (e.g., Flash) |
 +-------------+-----------------------+-------------------------+
 | Class 0, C0 | << 10 KiB             | << 100 KiB              |
 |             |                       |                         |
| Class 1, C1 | ~ 10 KiB              | ~ 100 KiB               |
|             |                       |                         |
| Class 2, C2 | ~ 50 KiB              | ~ 250 KiB               |

----
node.js requires >64MB up to 256MB

@danielpeintner What is the min size of a node-WoT device?

There are other device classes (gateways, directories) which are not in scope here.

**Comment by danielpeintner** [comment]
> node.js requires >64MB up to 256MB

I don't think limited devices will use node.js ...

> @danielpeintner What is the min size of a node-WoT device?

Mhh, very difficult question. I do not have a good frame for it.

What I would like to say is that I assume if plain JSON files cannot be processed people will use more efficient encoding formats which will make quite a difference...

**Comment by mlagally** [comment]
@danielpeintner 
we make a baseline assumption of a TCP/IP stack, HTTP(S), processing of JSON to happen on the consuming (and exposing) device, so other encoding formats are out of scope of this reference device.

**Comment by mlagally** [comment]
Arch call on 11.2.

There are some low profile Javascript runtimes that are more compact.
e.g.:
https://jerryscript.net/ which claims to run in 64k RAM / 256 K Flash
A Python implementation would also be an option.

 A C implementation of TLS for HTTPS fits into 32-64k
On an ESP 8266 there's 12k of RAM available for Javascript programs and variables.

https://www.esp8266.com/viewtopic.php?f=44&t=6574

# Number of interactions:

Length of a URL: 256 bytes -> 4 URLs in 1 k
128?

Guesstimate: (max 2k for URLs):
Base URL: 128 bytes
Rel parts: 64 bytes
Strong recommendation: use relative URLs

# TCP buffers:
1k / 1k send / receive

# Payload size: 
## HTTP Request: 
- Headers 256b
- JSON: 1-2k
## HTTP Response:
- Header 256b
- JSON (Full TD)

Pagination of a TD can help to mitigate size constraints -> Discovery TF

Working model: Store entire TD in a buffer.

**Comment by sebastiankb** [comment]
So, the [Smart Coffee Machine Thing](http://plugfest.thingweb.io:8083/smart-coffee-machine) with its 6xproperties, 2xactions, and 1xevent will not able support a TD following the profile since it needs 17k.

**Comment by danielpeintner** [comment]
Note1: In the smart-coffee-machine TD mentioned from Sebastian most of the text strings belong to `href`s:
* `"http://plugfest.thingweb.io:8083/smart-coffee-machine/..."`
* `"coap://plugfest.thingweb.io:5683/smart-coffee-machine/..."`
A clever implementation might provide a `base` to at least reduce the size of *one* protocol.

Another big part are descriptions that might be stripped.

Note2: I still doubt that very limited devices use plain JSON, see some out-of-the box achievements one can achieve with more optimized encodings (see http://exificient.github.io/javascript/demo/processJSON.html). Taking into account that some terms are known ahead of time like all know n terms the improvements can be much higher!

**Comment by sebastiankb** [comment]
Sure, the TD can be optimized, but let's assume there will be only 2 more actions, most likely we will again break the limit. The point is that we have introduce cool features such as `titles` and `descriptions` to share detail information for, e.g., mutli language UIs.  Such an use cases will be out of scope with such a limitation.

**Comment by sebastiankb** [comment]
[Here](https://vorto.eclipseprojects.io/api/v1/models/com.bosch.iot.suite.example.octopussuiteedition:OctopusSuiteEdition:1.1.0/content) is another example of a device description (from Vorto) that would never meet this constraint.

**Comment by sebastiankb** [comment]
>So, the Smart Coffee Machine Thing with its 6xproperties, 2xactions, and 1xevent will not able support a TD following the profile since it needs 17k.

sorry, the 17k is wrong. Its 9k

**Comment by mlagally** [comment]
I have created an initial strawman proposal in:
https://github.com/w3c/wot-profile/pull/69
Please comment and create PRs against it.

**Comment by sebastiankb** [comment]
Regarding Vorto: I have received the information from @kolotu that there is no limit specified for Vorto models.

**Comment by sebastiankb** [comment]
Just for information, Eclipse Edit{TD}or provides some statistics such as number of properties, actions, and events, as well as the size in kB. Here is an [example](https://eclipse.github.io/editdor/?td=%7B%22title%22:%22Smart-Coffee-Machine%22,%22description%22:%22A%20smart%20coffee%20machine%20with%20a%20range%20of%20capabilities.%5CnA%20complementary%20tutorial%20is%20available%20at%20http://www.thingweb.io/smart-coffee-machine.html.%22,%22support%22:%22git://github.com/eclipse/thingweb.node-wot.git%22,%22@context%22:%5B%22https://www.w3.org/2019/wot/td/v1%22,%7B%22@language%22:%22en%22%7D%5D,%22properties%22:%7B%22allAvailableResources%22:%7B%22type%22:%22object%22,%22description%22:%22Current%20level%20of%20all%20available%20resources%20given%20as%20an%20integer%20percentage%20for%20each%20particular%20resource.%5CnThe%20data%20is%20obtained%20from%20the%20machine's%20sensors%20but%20can%20be%20set%20manually%20via%20the%20availableResourceLevel%20property%20in%20case%20the%20sensors%20are%20broken.%22,%22readOnly%22:true,%22properties%22:%7B%22water%22:%7B%22type%22:%22integer%22,%22minimum%22:0,%22maximum%22:100%7D,%22milk%22:%7B%22type%22:%22integer%22,%22minimum%22:0,%22maximum%22:100%7D,%22chocolate%22:%7B%22type%22:%22integer%22,%22minimum%22:0,%22maximum%22:100%7D,%22coffeeBeans%22:%7B%22type%22:%22integer%22,%22minimum%22:0,%22maximum%22:100%7D%7D,%22writeOnly%22:false,%22observable%22:false,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/properties/allAvailableResources%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22%5D,%22htv:methodName%22:%22GET%22%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/properties/allAvailableResources%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22%5D%7D%5D%7D,%22availableResourceLevel%22:%7B%22type%22:%22number%22,%22description%22:%22Current%20level%20of%20a%20particular%20resource.%20Requires%20resource%20id%20variable%20as%20uriVariables.%5CnThe%20property%20can%20also%20be%20overridden,%20which%20also%20requires%20resource%20id%20as%20uriVariables.%22,%22uriVariables%22:%7B%22id%22:%7B%22type%22:%22string%22,%22enum%22:%5B%22water%22,%22milk%22,%22chocolate%22,%22coffeeBeans%22%5D%7D%7D,%22readOnly%22:false,%22writeOnly%22:false,%22observable%22:false,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/properties/availableResourceLevel%7B?id%7D%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22,%22writeproperty%22%5D%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/properties/availableResourceLevel%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22,%22writeproperty%22%5D%7D%5D%7D,%22possibleDrinks%22:%7B%22type%22:%22array%22,%22description%22:%22The%20list%20of%20possible%20drinks%20in%20general.%20Doesn't%20depend%20on%20the%20available%20resources.%22,%22readOnly%22:true,%22items%22:%7B%22type%22:%22string%22%7D,%22writeOnly%22:false,%22observable%22:false,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/properties/possibleDrinks%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22%5D,%22htv:methodName%22:%22GET%22%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/properties/possibleDrinks%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22%5D%7D%5D%7D,%22servedCounter%22:%7B%22type%22:%22integer%22,%22description%22:%22The%20total%20number%20of%20served%20beverages.%22,%22minimum%22:0,%22readOnly%22:false,%22writeOnly%22:false,%22observable%22:false,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/properties/servedCounter%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22,%22writeproperty%22%5D%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/properties/servedCounter%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22,%22writeproperty%22%5D%7D%5D%7D,%22maintenanceNeeded%22:%7B%22type%22:%22boolean%22,%22description%22:%22Shows%20whether%20a%20maintenance%20is%20needed.%20The%20property%20is%20observable.%20Automatically%20set%20to%20true%20when%20the%20servedCounter%20property%20exceeds%201000.%22,%22observable%22:true,%22readOnly%22:false,%22writeOnly%22:false,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/properties/maintenanceNeeded%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22,%22writeproperty%22%5D%7D,%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/properties/maintenanceNeeded/observable%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22observeproperty%22,%22unobserveproperty%22%5D,%22subprotocol%22:%22longpoll%22%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/properties/maintenanceNeeded%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22,%22writeproperty%22,%22observeproperty%22,%22unobserveproperty%22%5D%7D%5D%7D,%22schedules%22:%7B%22type%22:%22array%22,%22description%22:%22The%20list%20of%20scheduled%20tasks.%22,%22readOnly%22:true,%22items%22:%7B%22type%22:%22object%22,%22properties%22:%7B%22drinkId%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20what%20drink%20to%20make,%20drinkId%20is%20one%20of%20possibleDrinks%20property%20values,%20e.g.%20latte.%22%7D,%22size%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20the%20size%20of%20a%20drink,%20s%20=%20small,%20m%20=%20medium,%20l%20=%20large.%22,%22enum%22:%5B%22s%22,%22m%22,%22l%22%5D%7D,%22quantity%22:%7B%22type%22:%22integer%22,%22description%22:%22Defines%20how%20many%20drinks%20to%20make,%20ranging%20from%201%20to%205.%22,%22minimum%22:1,%22maximum%22:5%7D,%22time%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20the%20time%20of%20the%20scheduled%20task%20in%2024h%20format,%20e.g.%2010:00%20or%2021:00.%22%7D,%22mode%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20the%20mode%20of%20the%20scheduled%20task,%20e.g.%20once%20or%20everyday.%20All%20the%20possible%20values%20are%20given%20in%20the%20enum%20field%20of%20this%20Thing%20Description.%22,%22enum%22:%5B%22once%22,%22everyday%22,%22everyMo%22,%22everyTu%22,%22everyWe%22,%22everyTh%22,%22everyFr%22,%22everySat%22,%22everySun%22%5D%7D%7D%7D,%22writeOnly%22:false,%22observable%22:false,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/properties/schedules%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22%5D,%22htv:methodName%22:%22GET%22%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/properties/schedules%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readproperty%22%5D%7D%5D%7D%7D,%22actions%22:%7B%22makeDrink%22:%7B%22description%22:%22Make%20a%20drink%20from%20available%20list%20of%20beverages.%20Accepts%20drink%20id,%20size%20and%20quantity%20as%20uriVariables.%5CnBrews%20one%20medium%20americano%20if%20no%20uriVariables%20are%20specified.%22,%22uriVariables%22:%7B%22drinkId%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20what%20drink%20to%20make,%20drinkId%20is%20one%20of%20possibleDrinks%20property%20values,%20e.g.%20latte.%22%7D,%22size%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20the%20size%20of%20a%20drink,%20s%20=%20small,%20m%20=%20medium,%20l%20=%20large.%22,%22enum%22:%5B%22s%22,%22m%22,%22l%22%5D%7D,%22quantity%22:%7B%22type%22:%22integer%22,%22description%22:%22Defines%20how%20many%20drinks%20to%20make,%20ranging%20from%201%20to%205.%22,%22minimum%22:1,%22maximum%22:5%7D%7D,%22output%22:%7B%22type%22:%22object%22,%22description%22:%22Returns%20true/false%20and%20a%20message%20when%20all%20invoked%20promises%20are%20resolved%20(asynchronous).%22,%22properties%22:%7B%22result%22:%7B%22type%22:%22boolean%22%7D,%22message%22:%7B%22type%22:%22string%22%7D%7D%7D,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/actions/makeDrink%7B?drinkId,size,quantity%7D%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22invokeaction%22%5D,%22htv:methodName%22:%22POST%22%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/actions/makeDrink%22,%22contentType%22:%22application/json%22,%22op%22:%22invokeaction%22%7D%5D,%22idempotent%22:false,%22safe%22:false%7D,%22setSchedule%22:%7B%22description%22:%22Add%20a%20scheduled%20task%20to%20the%20schedules%20property.%20Accepts%20drink%20id,%20size,%20quantity,%20time%20and%20mode%20as%20body%20of%20a%20request.%5CnAssumes%20one%20medium%20americano%20if%20not%20specified,%20but%20time%20and%20mode%20are%20mandatory%20fields.%22,%22input%22:%7B%22type%22:%22object%22,%22properties%22:%7B%22drinkId%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20what%20drink%20to%20make,%20drinkId%20is%20one%20of%20possibleDrinks%20property%20values,%20e.g.%20latte.%22%7D,%22size%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20the%20size%20of%20a%20drink,%20s%20=%20small,%20m%20=%20medium,%20l%20=%20large.%22,%22enum%22:%5B%22s%22,%22m%22,%22l%22%5D%7D,%22quantity%22:%7B%22type%22:%22integer%22,%22description%22:%22Defines%20how%20many%20drinks%20to%20make,%20ranging%20from%201%20to%205.%22,%22minimum%22:1,%22maximum%22:5%7D,%22time%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20the%20time%20of%20the%20scheduled%20task%20in%2024h%20format,%20e.g.%2010:00%20or%2021:00.%22%7D,%22mode%22:%7B%22type%22:%22string%22,%22description%22:%22Defines%20the%20mode%20of%20the%20scheduled%20task,%20e.g.%20once%20or%20everyday.%20All%20the%20possible%20values%20are%20given%20in%20the%20enum%20field%20of%20this%20Thing%20Description.%22,%22enum%22:%5B%22once%22,%22everyday%22,%22everyMo%22,%22everyTu%22,%22everyWe%22,%22everyTh%22,%22everyFr%22,%22everySat%22,%22everySun%22%5D%7D%7D,%22required%22:%5B%22time%22,%22mode%22%5D%7D,%22output%22:%7B%22type%22:%22object%22,%22description%22:%22Returns%20true/false%20and%20a%20message%20when%20all%20invoked%20promises%20are%20resolved%20(asynchronous).%22,%22properties%22:%7B%22result%22:%7B%22type%22:%22boolean%22%7D,%22message%22:%7B%22type%22:%22string%22%7D%7D%7D,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/actions/setSchedule%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22invokeaction%22%5D,%22htv:methodName%22:%22POST%22%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/actions/setSchedule%22,%22contentType%22:%22application/json%22,%22op%22:%22invokeaction%22%7D%5D,%22idempotent%22:false,%22safe%22:false%7D%7D,%22events%22:%7B%22outOfResource%22:%7B%22description%22:%22Out%20of%20resource%20event.%20Emitted%20when%20the%20available%20resource%20level%20is%20not%20sufficient%20for%20a%20desired%20drink.%22,%22data%22:%7B%22type%22:%22string%22%7D,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/events/outOfResource%22,%22contentType%22:%22application/json%22,%22subprotocol%22:%22longpoll%22,%22op%22:%5B%22subscribeevent%22,%22unsubscribeevent%22%5D%7D,%7B%22href%22:%22ws://plugfest.thingweb.io:8083/smart-coffee-machine/events/outOfResource%22,%22contentType%22:%22application/json%22,%22op%22:%22subscribeevent%22%7D,%7B%22href%22:%22coap://plugfest.thingweb.io:5683/smart-coffee-machine/events/outOfResource%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22subscribeevent%22,%22unsubscribeevent%22%5D%7D%5D%7D%7D,%22@type%22:%22Thing%22,%22security%22:%5B%22nosec_sc%22%5D,%22id%22:%22urn:uuid:55f01138-5c96-4b3d-a5d0-81319a2db677%22,%22forms%22:%5B%7B%22href%22:%22http://plugfest.thingweb.io:8083/smart-coffee-machine/all/properties%22,%22contentType%22:%22application/json%22,%22op%22:%5B%22readallproperties%22,%22readmultipleproperties%22,%22writeallproperties%22,%22writemultipleproperties%22%5D%7D%5D,%22securityDefinitions%22:%7B%22nosec_sc%22:%7B%22scheme%22:%22nosec%22%7D%7D%7D).

**Comment by benfrancis** [comment]
I don't think defining a "Reference Device Definition for the smallest possible platform for HTTP / TCP / JSON" is possible. There are far too many variables. I propose closing.

**Comment by egekorkan** [comment]
I agree with the comment above. One thing we can do is document smallest profile conforming devices that someone has implemented. These wouldn't be references but would document this profile being possible in that kind of devices
