### ISSUE TITLE
Highlighting assertions

### ISSUE THREAD

**Issue by egekorkan** [w3c/wot-profile#74]
Similar to the TD spec, highlighting assertions in grey would greatly help with testing. @mmccool could you add the css file?

**Comment by mlagally** [comment]
See also #76 and #75

**Comment by mlagally** [comment]
This action also include a setup the tooling for the profile specification in the profile repo.

**Comment by benfrancis** [comment]
I think this is done now? Propose closing.

**Comment by mlagally** [comment]
We have assertion markup, closing the issue.
