### ISSUE TITLE
How to support composable "Vertical" vs. "Horizontal" Profiles

### ISSUE THREAD

**Issue by mmccool** [w3c/wot-profile#8]
The current spec addresses issues that are "Horizontal" and apply to all verticals, eg resource constraints.

However, there is also a need for profiles to address different market verticals, for example Smart Home vs. Industrial.   In particular, different vertical profiles may require support for different protocols and payload types.  For example, a Smart Home profile may require http and coap with json payloads and an Industrial profile might require opc-ua and xml payloads.

We have to consider use cases were we might need to compose these, for example, a Smart Building payload with lights following a Smart Home profile and an HVAC system following an Industrial profile.   In this case different profiles would be used with different Things, so the composability problem is not severe, but it might complicate things if we allow composite Things (eg components).

We may also need to compose a "Core" profile with a "vertical" profile, for example, to support Industrial devices by starting with a Core profile but adding support for OPC-UA.  So in this case, when we "compose" profiles, are we taking the intersection of constraints or the union of capabilities?   The former makes sense for allowed vocabulary terms, but the latter makes sense for allowed protocols and payload types.

**Comment by benfrancis** [comment]
I strongly recommend against defining vertical profiles at all. The core profile should be horizontal (cross-domain). Capability schemas allow domain-specific semantic annotations for different verticals which can be used as an enhancement. Vertical profiles for different application domains risk harming interoperability for no clear benefit. I can think of no technical reason why a smart home WoT client shouldn't be able to communicate with a health WoT device or a smart city WoT device for example.

I've commented elsewhere that I think the binary version of OPC-UA should be out of scope for a WoT Thing Description as it's a non-web protocol. The SOAP-based version could theoretically be described using "hypermedia controls", but a gateway implementation bridging OPC-UA to the WoT core profile is probably a better idea.

The only example I can currently think of where an additional profile might be desirable is a CoAP-based profile for resource constrained devices which physically can't implement the core profile. Again, that would be horizontal in nature.

**Comment by mlagally** [comment]
I think we should split the discussion into two parts to simplify it:
- Data Model Constraints
- Protocol Constraints

The Data Model constraints can be applied across diferent protocols and provide interoperability *across* different protocols. Thisis also useful for simulations etc.

Protocol constraints are per-protocol, and we should discuss which are reasonable for which protocols, and which protocols we should target.

**Comment by benfrancis** [comment]
What use cases are there for devices which don't fit the [TD Information Model](https://w3c.github.io/wot-thing-description/#sec-vocabulary-definition), and therefore require a different set of data model constraints? Could it be possible to simply modify the TD Information Model to make it more widely applicable?

Encouraging divergence in the data model risks harming interoperability, not helping it.

If all WoT devices can stick to the same data model, then only the "horizontal" protocol constraints are necessary.

**Comment by zolkis** [comment]
IMHO many of the constraints listed in section 4 of the Profiles spec make a lot of sense.
It's a great contribution to list all of those.
However, I agree they should be as a "baseline" in the TD spec. 
Divergence from there should be possible, but rare, and with assumed risk from "consumability" point of view. That would allow for a single TD spec.

**Comment by mlagally** [comment]
Composition etc. are not in the scope of the current requirements, this issue should be revisited after the publication of the first profile spec.

**Comment by mlagally** [comment]
Vertical profiles are currently out of of scope, we define a core profile in the 1.0 version of the profile spec.

**Comment by mlagally** [comment]
Vertical profiles are out of scope of Profile-1.x.Let's close this issue.
