### ISSUE TITLE
The policy for the assertions identified

### ISSUE THREAD

**Issue by chachamimm** [w3c/wot-profile#84]
As you know, I added <span> tags to the assertions identified with "must", "may", "should', "MUST", "MAY", and "SHOULD" for [PR82](https://github.com/w3c/wot-profile/pull/82).

However, I'm still not sure if all the changes were really relevant and would like to suggest we clarify the following:

1. How to assign Assertion IDs, e.g. based on (1) auto-generated sequential numbers, (2) numbers based on the section numbers or (3) summarized sentences of the Assertions themselves

2. If it's really OK to include the RFC2119 keywords in lower cases, i.e., "must", "may", and "should"

3. If we should include the non-RFC2119 keywords in upper cases, e.g., "MANDATORY"

I think we should have made clarification about those points before hand, but I noticed those problems after my first trial. So would sugget we clarify those questions, and ideally it would be better to generate some description about our policy as part of the Testing guideline.

What do you think?

**Comment by mlagally** [comment]
@chachamimm 
Thanks very much for your hard work in https://github.com/w3c/wot-profile/pull/82

Let me answer your questions:
> How to assign Assertion IDs, e.g. based on (1) auto-generated sequential numbers, (2) numbers based on the section numbers or (3) summarized sentences of the Assertions themselves

I think the chapter nubering scheme will change when we shift content around - I think brief summary based on the section header with a number are the way to go. 

> If it's really OK to include the RFC2119 keywords in lower cases, i.e., "must", "may", and "should"
We should align with the other WoT specifications, i.e. capitalize them. Can you please make this change?

> If we should include the non-RFC2119 keywords in upper cases, e.g., "MANDATORY"
We should reword these sentence and replace with the corresponding RFC2119 keyword (MUST)

**Comment by benfrancis** [comment]
@mlagally wrote:
> I think the chapter nubering scheme will change when we shift content around - I think brief summary based on the section header with a number are the way to go.

I agree. Please don't use section numbers in IDs since these are likely to change. I've already removed quite a lot of these.

**Comment by mlagally** [comment]
We have a consistent numbering of RFC assertions, closing the issue.
