### ISSUE TITLE
Should the Core Profile define a protocol binding for `observeproperty`/`unobserveproperty`?

### ISSUE THREAD

**Issue by benfrancis** [w3c/wot-profile#95]
Question raised by @egekorkan in https://github.com/w3c/wot-profile/pull/92#issuecomment-890259947:
> * I think there was a decision to not support `observeproperty` (and its similar friends). Is this decision still valid if this PR gets accepted?

I personally don't mind either way. Subscribing is the primary (default) use case of an event affordance, whereas observing is arguably more of a nice-to-have for a property. I wouldn't be opposed to defining a protocol binding for `observeproperty`/`unobserveproperty` using Server-Sent Events (to reduce implementation complexity) as an optional feature of the Core Profile.

I think it could be fairly straightforward using HTTP content negotiation to choose between reading a static JSON value vs. observing an event stream, we'd just need to decide what to use as the event name (use the property name?).

**Comment by egekorkan** [comment]
In the case of node-wot, the observation via longpoll happens on another href like `/myproperty/observable` which is not RESTful (if observing is RESTful) since the same resource has two URIs. This is of course only for a Thing implementation. The Consumer just uses the href with the given op value/method anyways.

**Comment by benfrancis** [comment]
In the case of WebThings, we currently use WebSockets for observing properties which also has a separate URL to reading the property, because a single WebSocket endpoint is shared across the whole device. E.g. https://foo.webthings.io/things/lamp1/properties/on vs. wss://foo.webthings.io/things/lamp1

If the Core Profile used Server-Sent Events for observing I can imagine something like the below for both interaction-level and top-level forms.

```json
{
  "@context": "https://www.w3.org/2019/wot/td/v1",
  "id": "https://mywebthingserver.com/things/lamp",
  "profile": "https://www.w3.org/2021/wot/profile/core",
  "base": "https://mywebthingserver.com/things/lamp/",
  "title": "My Lamp",
  "description": "A web connected lamp",
  "securityDefinitions": {
    "oauth2": {
      "scheme": "oauth2",
      "flow": "code",
      "authorization": "https://mywebthingserver.com/oauth/authorize",
      "token": "https://mywebthingserver.com/oauth/token",
    }
  },
  "security": "oauth2",
  "properties": {
    "on": {
      "type": "boolean",
      "title": "On/Off",
      "description": "Whether the lamp is turned on",
      "forms": [
         {
            "op": ["readproperty", "writeproperty"],
            "href": "./properties/on"
         },
         {
            "op": ["observeproperty", "unobserveproperty"],
            "href": "./properties/on",
            "subprotocol": "sse"
        }
      ]
    },
    "level" : {
      "type": "integer",
      "title": "Brightness",
      "description": "The level of light from 0-100",
      "minimum" : 0,
      "maximum" : 100,
      "forms": [
         {
            "op": ["readproperty", "writeproperty"],
            "href": "./properties/level"
         },
         {
            "op": ["observeproperty", "unobserveproperty"],
            "href": "./properties/level",
            "subprotocol": "sse"
        }
      ]
    }
  },
  "actions": {
    "fade": {
      "title": "Fade",
      "description": "Fade the lamp to a given level",
      "input": {
        "type": "object",
        "properties": {
          "level": {
            "type": "integer",
            "minimum": 0,
            "maximum": 100
          },
          "duration": {
            "type": "integer",
            "minimum": 0,
            "unit": "milliseconds"
          }
        }
      },
      "forms": [
        {
           "href": "./actions/fade",
           "op:": "invokeaction"
        }
      ]
    }
  },
  "events": {
    "overheated": {
      "title": "Overheated",
      "data": {
        "type": "number",
        "unit": "degree celsius"
      },
      "description": "The lamp has exceeded its safe operating temperature",
      "forms": [
         {
            "href": "./events/overheated",
            "op": ["subscribeevent", "unsubscribeevent"],
            "subprotocol": "sse"
        }
      ]
    }
  },
  "forms": [
    {
      "op": ["readallproperties", "writemultipleproperties"],
      "href": "./properties"
    },
    {
      "op": ["observeallproperties", "unobserveallproperties"],
      "href": "./properties",
      "subprotocol": "sse"
    },
    {
      "op": ["subscribeallevents", "unsubscribeallevents"],
      "href": "./events"
    }
  ],
  "links": [
    {
      "rel": "alternate",
      "type": "text/html",
      "href": "."
    }
  ]
}
```

**Comment by benfrancis** [comment]
We need to reach a consensus on this before publication of 1.0.

My current thinking is that we can leave out observing properties from the Core Profile. I would be OK with providing a protocol binding based on SSE, but it doesn't fit quite as neatly as with events because I assume the name of the property would have to be mapped onto the "event" field in an event stream, which is potentially a bit confusing.

We could also punt this to 2.0.
