### ISSUE TITLE
Server Sent Events section to reference a stable reliable specification

### ISSUE THREAD

**Issue by mlagally** [w3c/wot-profile#98]
Since the WHATWG spec is a "living document" outide of our control,
it may introduce incompatible changes that we are not aware of.

Therefore our fallback approach is to reference the official 
https://www.w3.org/TR/eventsource/ specification satisfies our requirements
and is a stable basis, we will use it as a reference.

We hope that the superseded W3C document will be updated and aligned 
with the living WHATWG spec in the future.
In that case we will reference the latest W3C document.

**Comment by benfrancis** [comment]
We discussed this in a meeting and ended up switching it back to the WHATWG specification. Are we OK with that as the final decision (the W3C specification is marked as deprecated)? For the record, I'm fine with it.

**Comment by mlagally** [comment]
I agree, let's close this issue.
